fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,15 +31,15 @@ jobs:
       - name: Debug
         run: |
           echo "${GITHUB_WORKSPACE}/dependencies:"
-          ls -l ${GITHUB_WORKSPACE}/dependencies
+          ls -l ${GITHUB_WORKSPACE}/dependencies || echo "Error"
           echo "${GITHUB_WORKSPACE}/dependencies/venv:"
-          ls -l ${GITHUB_WORKSPACE}/dependencies/venv
-          echo "${GITHUB_WORKSPACE}/dependencies/venv:"
-          ls -l ${GITHUB_WORKSPACE}/dependencies/view
+          ls -l ${GITHUB_WORKSPACE}/dependencies/venv || echo "Error"
+          echo "${GITHUB_WORKSPACE}/dependencies/view:"
+          ls -l ${GITHUB_WORKSPACE}/dependencies/view || echo "Error"
           echo "${GITHUB_WORKSPACE}/dependencies/venv/lib64/cmake:"
-          ls -l ${GITHUB_WORKSPACE}/dependencies/venv/lib64/cmake
-          echo "${GITHUB_WORKSPACE}/dependencies/venv/lib64/cmake:"
-          ls -l ${GITHUB_WORKSPACE}/dependencies/view/lib64/cmake
+          ls -l ${GITHUB_WORKSPACE}/dependencies/venv/lib64/cmake || echo "Error"
+          echo "${GITHUB_WORKSPACE}/dependencies/view/lib64/cmake:"
+          ls -l ${GITHUB_WORKSPACE}/dependencies/view/lib64/cmake || echo "Error"
 
       - name: Build wheels
         uses: pypa/cibuildwheel@v3.3.1
